---
title: Tellen op een micro:bit
hero_image: images/banner.png
description: Een telling bijhouden op een micro:bit
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Tellen op een micro:bit
