title: Counting up on a micro:bit
hero_image: images/banner.png
description: Keeping count on a micro:bit
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Counting on a micro:bit
